// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Helloworld.proto

package helloworld;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 sex = 2;</code>
   */
  int getSex();

  /**
   * <code>int32 age = 3;</code>
   */
  int getAge();
}
